[project]
name = "projeto-tech-challenge-sistema-triagem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.4.2",
    "download>=0.3.5",
    "dvc>=3.67.1",
    "en-core-web-sm>=3.8.0",
    "httpx>=0.28.1",
    "matplotlib>=3.11.1",
    "nbstripout>=0.9.1",
    "nltk>=3.10.0",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "spacy>=3.8.14",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
